name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}

permissions:
  zjoin.setspawn:
    description: Permiso para establecer un spawn

commands:
  setspawn:
    description: Establecer el spawn del servidor
    usage: /<command>
  spawn:
    description: Ir al spawn establecido
    usage: /<command>